---
title: "Forecasting Personal Consumption Expenditures using Bayesian VARs and Alternative Data"
author: "Victoria Sonnemans"

execute:
  echo: false
  
bibliography: references.bib
---

```{css, echo = FALSE}
.justify {
text-align: justify !important
}
```

::: {.justify}
> **Abstract.** Can Bayesian VARs and alternative data help better estimate the future state of household final consumption expenditures in Australia? Which combination of traditional and alternative data provides the highest accuracy in the latter indicator? As household consumption is a major component of GDP, this research project will study the potential use of Bayesian VARs with a mix of traditional economic data such as disposable income and an alternative data source which is Google Trends to forecast this indicator.

> **Keywords.** Bayesian Vars, Google Trends, new data types

## The question, objective and motivation

### Research question

Can Bayesian VARs and alternative data help better estimate the future state of household final consumption expenditures in Australia? Which combination of traditional and alternative data provides the highest accuracy in the latter indicator?

### Objective and Motivation

As it drives around 50% of the Australian GDP, Household Final Consumption Expenditures (PCE) is a leading indicator to gauge the economic health of a country. There is thus a high incentive to improve the accuracy of its predictions. This has encouraged researchers to investigate big data as alternative sources. For instance, Schimdt and Vosen (2009) use search query time-series provided by Google Trends to forecast consumption. Esteves (2009), Aprigliano, et al. (2019), Galbraith and Tkacz (2013), Carlsen and Storgaard (2010) analyze electronic payments to predict consumption as these can track a large percentage of spending activities. Ellingsen, et al. (2021) demonstrate that news media data capture information about consumption that hard economic indicators do not. Gil et al. (2018) investigate the potential of the Economic Policy Uncertainty index derived from news data and developed by Baker et al. (2016) to predict consumption.

According to Professor Tomasz Wozniak from the University of Melbourne, forecasting with Bayesian VARs often leads to more precise forecasts than when using the frequentist approach to forecasting because of the effect of the priors. Despite the benefits of Bayesian VARs, there is nearly no research on the combination of Bayesian VARs and alternative data. Existing articles either investigate the use of Bayesian estimation models or of alternative data to forecast indicators but do not consider both together.

This paper will compare the forecasts of PCE in Australia from Bayesian VARs and several extensions applied on different sets of variables. These datasets will include both traditional macroeconomic variables computed by statistical offices and alternative data such as Google Trends. This research project contributes to the literature by studying PCE, an indicator that has to date received scant attention from the Bayesian VARs literature. Moreover, it proposes the first investigation of the combination of Bayesian VARs with alternative data to forecast PCE.

## The data and their properties

To forecast PCE, we will construct a dataset which contains two types of variables: traditional macroeconomic indicators and alternative variables.

The traditional variables included in this analysis were collected from the readrba package and will be:

-   Household final consumption expenditure

-   Real household disposable income

-   Consumer sentiment indicator

-   Consumer Price Index

Incorporating traditional economic variables along alternative data in this exercise is important as we do not want to fall in the "Big Data hubris" trap introduced by (Lazer et al., 2014). The "Big Data Hubris" is the problematic assumption that alternative data or big data can be used as a replacement for traditional data rather than a supplement. To prevent this, combining non-standard and standard variables together can lead to greater value. Moreover, previous extensive literature already has recognized the predictive power of these macroeconomic variables. For instance, previous research have identified co-movements of most common consumer sentiment indicators and real PCE (Schimdt and Vosen, 2009). 

##### Figure 1. Time series plots of the variables {style="text-align: center;"}

```{r setup, echo = F, warning=FALSE, message = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
suppressWarnings({
library(readrba)
library(xts)
library(tseries)
library(ggplot2)
library(patchwork)
library(dygraphs)
library(timeDate)
library(readabs)
library(zoo)
library(RColorBrewer)

#Our variables
#Household final consumption expenditures 
pce = na.omit(as.data.frame(read_rba(series_id = "GGDPECCVPSH")))  
pce = pce[203:254,]
pce$date = as.Date(as.character(pce$date),format="%Y-%m-%d")  

#Real household disposable income
inc = na.omit(as.data.frame(read_rba(series_id = "GGDPICHRDI")))  
inc = inc[203:254,]
inc$date = as.Date(as.character(inc$date),format="%Y-%m-%d")  

#Consumer sentiment indicator
sent = na.omit(as.data.frame(read_rba(series_id = "GICWMICS")))  
sent$date = as.Date(as.character(sent$date),format="%Y-%m-%d")  


#Inflation-Consumer Price Index
cpi = na.omit(as.data.frame(read_rba(series_id = "GCPIAG"))) 
cpi = cpi[352:403,]
cpi$date = as.Date(as.character(cpi$date),format="%Y-%m-%d")  



plot_pce <- ggplot(data=pce, aes(x=date, y=value))+ scale_y_continuous(labels=scales::comma_format(big.mark=','))+ xlab(NULL)+ ylab(NULL) + geom_line(color="#8DD3C7") +ggtitle("PCE") + theme(plot.title = element_text(size=12))+ theme_minimal()
plot_inc <- ggplot(data=inc, aes(x=date, y=value)) + xlab(NULL)+ ylab(NULL)+ scale_y_continuous(labels=scales::comma_format(big.mark=',')) + geom_line(color="#8DD3C7") +ggtitle("Real household disposable income") + theme(plot.title = element_text(size=12))+ theme_minimal()
plot_sent <- ggplot(data=sent, aes(x=date, y=value)) + xlab(NULL)+ ylab(NULL)+ scale_y_continuous(labels=scales::comma_format(big.mark=',')) + geom_line(color="#BEBADA") +ggtitle("Consumer sentiment indicator") + theme(plot.title = element_text(size=12))+ theme_minimal()
plot_cpi <- ggplot(data=cpi, aes(x=date, y=value)) + xlab(NULL)+ ylab(NULL)+ scale_y_continuous(labels=scales::comma_format(big.mark=',')) + geom_line(color="#BEBADA") +ggtitle("Consumer Price Index") + theme(plot.title = element_text(size=12))+ theme_minimal()
plot_pce+plot_inc+plot_sent+plot_cpi + plot_layout(heights = c(3,3))})

```

------------------------------------------------------------------------

As for the alternative data, a Google Trends index will be included. Google Trends is a tool which reveals how frequently a certain keyword has been searched for on the Google web browser. The platform provides weekly aggregated time series starting in 2004 for a specific keyword that can be directly downloaded using the R package "gtrendsR". The Google Trends index will be constructed based on the methodology presented in Schmidt and Vosen (2009). However, we will adapt their approach to match Australian specifies. Therefore, the specific keywords to construct the index have yet to be chosen. Moreover, Google Trends have been quite extensively studied to forecast labor market indicators but only a few articles have focused on PCE.

## The model

The model used for the forecasting experiment is a VAR(p) model:

$$
\begin{aligned}
y_t & =\mu_0+A_1 y_{t-1}+\cdots+A_p y_{t-p}+\epsilon_t \\\epsilon_t \mid Y_{t-1} & \sim i i d \mathcal{N}_N\left(\mathbf{0}_N, \Sigma\right)
\end{aligned}
$$

Where $N=5$ and $y_t$ is the vector of 6 variables:

$$
y_t=\left(\begin{array}{cc}\operatorname{pce}_t & =\text { PCE } \\\operatorname{GT}_t & =\text { Google Trends index } \\\operatorname{inc}_t & =\text { Real household disposable income } \\\text { sent }_t & =\text { Consumer sentiment indicator }\\\text { cpi }_t & =\text { Consumer price index } 
\end{array}\right)
$$

The model can also be written in matrix notation:

$$
\begin{aligned}
Y & =X A+E \\E \mid X & \sim \mathcal{M N} _{T \times N}\left(\mathbf{0}_{T \times N}, \Sigma, I_T\right)
\end{aligned}
$$

Where $Y$ is a $T\times5$ matrix, $X$ is a $T\times(1+(5\times p))$, $A$ is a $(1+(5\times p))\times 5$ matrix that contains the relationships between the variables and $E$ is a $T\times5$. T and p are yet to be determined during the continuation of this research project.

In the continuation of this research project, we will make assumptions on the priors distribution and a possible extension of this model could be to check if other priors could lead to better results. Moreover, we will estimate the matrix A to understand the relationship between those variables. The objective will be to identify whether alternative data can improve the forecast accuracy of PCE.

## References

Aprigliano, V., Ardizzi, G., & Monteforte, L. (2019), "Using Payment System Data to Forecast Economic Activity," International Journal of Central Banking, International Journal of Central Banking, vol. 15(4), pages 55-80, October.

Baker, S. R., Bloom, N., & Davis, S. J. (2016). Measuring Economic Policy Uncertainty. The Quarterly Journal of Economics, 131(4), 1593--1636. https://doi.org/10.1093/qje/qjw024

Carlsen, M. & Storgaard, P. E. (2010), "Dankort Payments as a Timely Indicator of Retail Sales in Denmark." Danmarks Nationalbank Working Papers n°66.

Ellingsen, J., Larsen, V. H., & Thorsrud, L. A. (2021). News media versus FRED‐MD for macroeconomic forecasting. Journal of Applied Econometrics, 37(1), 63 -- 81. https://doi.org/10.1002/jae.2859.

Esteves, P. S. (2009), "Are ATM/POS Data Relevant When Nowcasting Private Consumption?", Working Papers n°25, Banco de Portugal.

Galbraith, J. W., & Tkacz, G. (2013). Nowcasting GDP: Electronic Payments, Data Vintages and the Timing of Data Releases. SSRN Electronic Journal. https://doi.org/10.2139/ssrn.2342228.

Gil, M., Perez, J. J., Sanchez Fuentes, A. J., & Urtasun, A. (2018). "Nowcasting Private Consumption: Traditional Indicators, Uncertainty Measures, Credit Cards and Some Internet Data", Working Paper No. 1842, Banco de Espana.

Lazer, D., Kennedy, R., King, G., & Vespignani, A. (2014). The Parable of Google Flu: Traps in Big Data Analysis. Science (New York, N.Y.), 343, 1203--1205. https://doi.org/10.1126/science.1248506

Schmidt, T., & Vosen, S. (2009). Forecasting Private Consumption: Survey-Based Indicators vs. Google Trends. Journal of Forecasting, 30. https://doi.org/10.2139/ssrn.1514369

:::
